/**
   NumberGuessingGame.java      

   Uses while loops and if statements in a guessing game. 
   The user is guided towards correctly guessing a computer-generated number
   And can exit the game by inputting 0. 

   @Author: Caitlin Duquette

   @Version: 02/16/2026
**/


//import necessary classes
import java.util.Scanner;

public class NumberGuessingGame
{
   public static void main (String[] args)
   {

    // Declare all variables and constants
    final int SENTINEL = 0; 
    int userNum;
    int compNum = (int)(Math.random() * 100) + 1; // Generate and save a random integer between 1 - 100


    // Create the Scanner "variable" object for input
    Scanner keyboard = new Scanner(System.in);
    
    // Display the program's purpose or introduction
    System.out.println("Welcome to the Guessing Game! "); 
    System.out.println("Guess the number generated by the computer to win. "); 
    System.out.println("Enter 0 to quit the game. ");
    System.out.println(); 
   

    //Ask user to guess an integer
    System.out.print("Guess a number between 1 and 100: ");     
    userNum = keyboard.nextInt();
    
    System.out.println();   

    // (LOOP) Continue to ask the user to enter a guess while their answer is
    // not correct and the number entered is not 0.
    while (userNum != SENTINEL && userNum != compNum)
    {
        if (userNum < compNum)  //check if guess is 0, lower, higher or equal to computer-generated number
        {
            System.out.println("Your guess is too low! Try again. ");
            System.out.println(); 
        }
        else 
        {
            System.out.println("Your guess is too high! Try again. "); 
            System.out.println(); 
        }
        
        System.out.print("Enter another number between 1 and 100, or 0 to quit: ");
        userNum = keyboard.nextInt(); 
    }
         
         
    System.out.println(); 
    System.out.println();
    
    // Display the computer's answer
    // Displaying the result
    System.out.println("The computer's number: " +compNum); 
    
    if (userNum == compNum)
    {
        System.out.println("Your number: " +userNum); 
        System.out.println("You guess correct! You're a pro! "); 
    }
    else if (userNum == SENTINEL)
    {
        System.out.println("You quit the game :'( please try again. ");
    }
    


       
    } 
}
